var asseblycodetabledata = [
    ['opcode','parameters','explantion'],
    ['mul','','regb = rega * regb'],
    ['div','','regb = rega / regb'],
    ['sub','','regb = rega - regb'],
    ['load','reg,val','load val into reg'],
    ['store','reg,adr','store register at adres'],
    ['and','','regb = rega & regb'],
    ['or','','regb = rega | regb'],
    ['dregb','','dreference value in register b'],
    ['set','adr,value','sets value at adres'],
    ['add','adr,value','adds val to adres'],
    ['incr','adr','adds 1 to adres'],
    ['cmp','vala,valb',' compares 2 values and sets flags'],
    ['branch','to,negativeflag,zeroflag','go to address if flags are set'],
    ['jmp','to','go to address'],
    ['noop','','do nothing'],
    ['print','value','print value'],
    ['halt','','stop program'],
]

var machinecodetabledata = [
    ['machine code','instruction name','size','parameters','explanation'],
    ['0','noop','1','','do nothing'],
    ['1','dref','3','reg,adr',''],
    ['2','dreg','2','reg','dereferences value in specified register'],
    ['3','drega','1','','dereferences value in register a'],
    ['4','dregb','1','','dereferences value in register b'],
    ['5','add','1','','+'],
    ['6','sub','1','','-'],
    ['7','mul','1','','*'],
    ['8','div','1','','/'],
    ['9','or','1','','|'],
    ['10','and','1','','&'],
    ['11','cmp','1','','rega - regb and sets flags'],
    ['12','jmp','1','','jumps to address in register b'],
    ['13','branch','3','negflag,zeroflag','jumps to address in register b if flags match the given parameters'],
    ['14','call','1','',''],
    ['15','ret','1','',''],
    ['16','load','3','register,val','loads value in specified register'],
    ['17','store','3','register,adr','stores specified register at address'],
    ['18','print','1','','prints value in register b'],
    ['19','halt','1','','jumps to end of memory'],
]
